spring.data.mongodb.uri: mongodb://localhost:27020/messaging

kafka:
    topic: "file-share-expiration"
    url: localhost:9003

mail:
    username:
    password:
    from: "test@test.com"
    host:
    port:
    protocol:
    smtp:
        auth:
        starttls.enable: